export const actionFilterList = {
  // DATE
  INIT_DAY: 'INIT_DAY',
  PICK_DATE: 'PICK_DATE',
  INIT_CURRENT_DATE_BY_DAY: 'INIT_CURRENT_DATE_BY_DAY',
  INIT_CURRENT_DATE: 'INIT_CURRENT_DATE',

  // MONTH
  INIT_MONTH: 'INIT_MONTH',
  RE_INIT_MONTH: 'RE_INIT_MONTH',
  PICK_MONTH: 'PICK_MONTH',
  PREV_MONTH: 'PREV_MONTH',
  NEXT_MONTH: 'NEXT_MONTH',

  // YEAR
  INIT_YEAR: 'INIT_YEAR',
  PICK_YEAR: 'PICK_YEAR',
  PREV_YEAR: 'PREV_YEAR',
  NEXT_YEAR: 'NEXT_YEAR',

  // DISPLAY
  DISPLAY: 'DISPLAY'
}